# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import auth_pb2 as auth__pb2


class AuthStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPublicKey = channel.unary_unary(
        '/auth.Auth/GetPublicKey',
        request_serializer=auth__pb2.Empty.SerializeToString,
        response_deserializer=auth__pb2.PublicKey.FromString,
        )
    self.LoginUser = channel.unary_unary(
        '/auth.Auth/LoginUser',
        request_serializer=auth__pb2.Login.SerializeToString,
        response_deserializer=auth__pb2.SignedToken.FromString,
        )
    self.VerifyToken = channel.unary_unary(
        '/auth.Auth/VerifyToken',
        request_serializer=auth__pb2.SignedToken.SerializeToString,
        response_deserializer=auth__pb2.Token.FromString,
        )
    self.RenewToken = channel.unary_unary(
        '/auth.Auth/RenewToken',
        request_serializer=auth__pb2.SignedToken.SerializeToString,
        response_deserializer=auth__pb2.SignedToken.FromString,
        )


class AuthServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPublicKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoginUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifyToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RenewToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPublicKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetPublicKey,
          request_deserializer=auth__pb2.Empty.FromString,
          response_serializer=auth__pb2.PublicKey.SerializeToString,
      ),
      'LoginUser': grpc.unary_unary_rpc_method_handler(
          servicer.LoginUser,
          request_deserializer=auth__pb2.Login.FromString,
          response_serializer=auth__pb2.SignedToken.SerializeToString,
      ),
      'VerifyToken': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyToken,
          request_deserializer=auth__pb2.SignedToken.FromString,
          response_serializer=auth__pb2.Token.SerializeToString,
      ),
      'RenewToken': grpc.unary_unary_rpc_method_handler(
          servicer.RenewToken,
          request_deserializer=auth__pb2.SignedToken.FromString,
          response_serializer=auth__pb2.SignedToken.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'auth.Auth', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
