# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import info_pb2 as info__pb2


class InfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSystem = channel.unary_unary(
        '/info.Info/GetSystem',
        request_serializer=info__pb2.Empty.SerializeToString,
        response_deserializer=info__pb2.System.FromString,
        )


class InfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSystem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSystem': grpc.unary_unary_rpc_method_handler(
          servicer.GetSystem,
          request_deserializer=info__pb2.Empty.FromString,
          response_serializer=info__pb2.System.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'info.Info', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
